import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity/visual-editing";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import { Navbar } from "@/components/Navbar";
import { client } from "@/lib/sanity/client";
import { NAVBAR_QUERY } from "@/lib/sanity/query";
import type { Navbar as NavbarType } from "@/lib/sanity/sanity.types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const dm = await draftMode();
  const navbar = await client.fetch<NavbarType | null>(NAVBAR_QUERY, {}, {
    perspective: dm.isEnabled ? "previewDrafts" : "published",
    next: { revalidate: dm.isEnabled ? 0 : 30 },
  });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar data={navbar} />
          {children}

          {dm.isEnabled && (
            <>
              <VisualEditing />
              <DisableDraftMode />
            </>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
